
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/master0?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin


mybatis:
  mapper-locations: classpath*:mapper/*.xml


